services:
  server2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-web-server-lab2
    environment:
      PORT: 8001
      MAX_WORKERS: 16
      SIMULATE_WORK_MS: 0
    ports:
      - "8001:8001"
    volumes:
      - ./public:/serve:ro        
    command: ["python", "server_mt.py", "/serve"]
